version: "3.10"
services:
  fastapi:
    build: api/
    ports:
      - "80:80"
    # networks:
    #   - app_network

  streamlit:
    build: streamlit/
    ports:
      - "8501:8501"
    # networks:
    #   - app_network
    depends_on:
      - fastapi
# networks:
#   app_network:
#     driver: bridge
